name: tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run:
          pip install -r requirements.txt
          pip install coveralls
      - name: Coveralls
        run: coveralls
        env:
          github-token: ${{ secrets.GITHUB-TOKEN }}