name: tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coveralls
      - name: Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB-TOKEN }}