name: tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coveralls
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
      - name: Start PostgreSQL
        run:
          sudo systemctl start postgresql.service
      - name: Test query
        run:
          psql -U db_admin -d department_app.db --command="select department_app_department.name, department_app_employee.name from department_app_employee inner join department_app_department on department_app_employee.related_department_id = department_app_department.id;"
