name: tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run:
          pip install -r requirements.txt
          pip install coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secret.GITHUB-TOKEN }}